name: Use Reusable Workflow

on:
  issues:
    types: [edited]
  pull_request:
    types: [edited]

jobs:
  get-project-id:
    uses: jarmak-nv/shared-workflows/.github/workflows/project-get-item-id.yaml@project-automation-components
    secrets: inherit
    with:
      PROJECT_ID: "PVT_kwHOBjnxfs4AEt2h"
      ITEM_NODE_ID: "${{ github.event.pull_request.node_id }}"

  update-sprint:
    uses: jarmak-nv/shared-workflows/.github/workflows/project-get-set-iteration-field.yaml@project-automation-components
    needs: get-project-id
    with:
      PROJECT_ID: "PVT_kwHOBjnxfs4AEt2h"
      ITERATION_FIELD_ID: "PVTIF_lAHOBjnxfs4AEt2hzgL0kXY"
      ITERATION_FIELD_NAME: "Sprint"
      ITEM_PROJECT_ID: "${{ needs.get-project-id.outputs.ITEM_PROJECT_ID }}"
      ITEM_NODE_ID: "${{ github.event.pull_request.node_id }}"
      UPDATE_ITEM: true
      UPDATE_LINKED_ISSUES: true
    secrets: inherit

  update-status:
    uses: jarmak-nv/shared-workflows/.github/workflows/project-get-set-iteration-field.yaml@project-automation-components
    needs: get-project-id
    with:
      PROJECT_ID: "PVT_kwHOBjnxfs4AEt2h"
      SINGLE_SELECT_FIELD_ID: "PVTSSF_lAHOBjnxfs4AEt2hzgCt50s"
      SINGLE_SELECT_FIELD_NAME: "Status"
      SINGLE_SELECT_OPTION_VALUE: "In Progress"
      ITEM_PROJECT_ID: "${{ needs.get-project-id.outputs.ITEM_PROJECT_ID }}"
      ITEM_NODE_ID: "${{ github.event.pull_request.node_id }}"
      UPDATE_ITEM: true
      UPDATE_LINKED_ISSUES: true
    secrets: inherit
